<?php

namespace AppBundle\Repository;

/**
 * deviseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class deviseRepository extends \Doctrine\ORM\EntityRepository
{
}
