<?php

namespace AppBundle\Repository;

/**
 * fournisseursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class fournisseursRepository extends \Doctrine\ORM\EntityRepository
{
}
