<?php

namespace AppBundle\Repository;

/**
 * produits_revendeursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class produits_revendeursRepository extends \Doctrine\ORM\EntityRepository
{
}
