<?php

namespace AppBundle\Repository;

/**
 * proposition_fournisseursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class proposition_fournisseursRepository extends \Doctrine\ORM\EntityRepository
{
}
