<?php

namespace AppBundle\Repository;

/**
 * type_produitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class type_produitRepository extends \Doctrine\ORM\EntityRepository
{
}
