<?php

namespace AppBundle\Repository;

/**
 * vendeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class vendeRepository extends \Doctrine\ORM\EntityRepository
{
}
