Abonnement\RevendeurBundle\Entity\Revendeur:
    type: entity
    table: null
    repositoryClass: Abonnement\RevendeurBundle\Repository\RevendeurRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        
