<?php

namespace AppBundle\Repository;

/**
 * appareilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class appareilRepository extends \Doctrine\ORM\EntityRepository
{
}
