<?php

namespace AppBundle\Repository;

/**
 * clientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class clientRepository extends \Doctrine\ORM\EntityRepository
{
}
