<?php

namespace AppBundle\Repository;

/**
 * statfourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class statfourRepository extends \Doctrine\ORM\EntityRepository
{
}
