<?php

namespace AppBundle\Repository;

/**
 * vendeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class vendeRepository extends \Doctrine\ORM\EntityRepository
{
    public function myFindAll()
  {
    $queryBuilder = $this->createQueryBuilder('V');

    $queryBuilder = $this->_em->createQueryBuilder()
                              ->select('V' , 'P.id')
                              ->from($this->vende, 'V')
                              ->leftjoin('AppBundle:produits' , 'P')
                              ->where( 'P.id = V.produits and P.vendu = 0');
    $query = $queryBuilder->getQuery();
 
  }
}

