app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /
app:
    resource: "@AppBundle/Controller/"
    type: rest
    prefix: /api
api_login_check:
    path: /api/login_check

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"



