abonnement_revendeur:
    resource: "@AbonnementRevendeurBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /admin

admin_homepage:
    path:     /admin
    defaults: { _controller: AppBundle:Default:admin }

home:
    path:     /
    defaults: { _controller: AppBundle:Default:index }
    
homepage:
    path:     /home
    defaults: { _controller: AppBundle:home:index }

revendeur_home:
    path:     /{user}/revendeur
    defaults: { _controller: AppBundle:Revendeur:home }

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"



