app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /admin
app:
    resource: "@AppBundle/Controller/"
    type: rest
    prefix: /api
api_login_check:
    path: /api/login_check

admin_homepage:
    path:     /admin
    defaults: { _controller: AppBundle:Default:index }
    
homepage:
    path:     /home
    defaults: { _controller: AppBundle:home:index }

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"



