abonnement_revendeur_revendeur:
    resource: "@AbonnementRevendeurBundle/Resources/config/routing/revendeur.yml"
    prefix:   /{user}/revendeur

abonnement_revendeur_homepage:
    path:     /{user}/revendeur_home
    defaults: { _controller: AbonnementRevendeurBundle:Default:index }
