fournisseurs_index:
    path:     /
    defaults: { _controller: "AppBundle:fournisseurs:index" }
    methods:  GET

fournisseurs_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:fournisseurs:show" }
    methods:  GET

fournisseurs_new:
    path:     /new
    defaults: { _controller: "AppBundle:fournisseurs:new" }
    methods:  [GET, POST]

fournisseurs_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:fournisseurs:edit" }
    methods:  [GET, POST]

fournisseurs_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:fournisseurs:delete" }
    methods:  DELETE
