produits_revendeurs_index:
    path:     /
    defaults: { _controller: "AppBundle:produits_revendeurs:index" }
    methods:  GET

produits_revendeurs_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:produits_revendeurs:show" }
    methods:  GET

produits_revendeurs_new:
    path:     /new
    defaults: { _controller: "AppBundle:produits_revendeurs:new" }
    methods:  [GET, POST]

produits_revendeurs_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:produits_revendeurs:edit" }
    methods:  [GET, POST]

produits_revendeurs_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:produits_revendeurs:delete" }
    methods:  DELETE
