<?php

namespace Abonnement\RevendeurBundle\Repository;

/**
 * produit_revRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class produit_revRepository extends \Doctrine\ORM\EntityRepository
{
}
