<?php

namespace Abonnement\RevendeurBundle\Repository;

/**
 * RevendeurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RevendeurRepository extends \Doctrine\ORM\EntityRepository
{
}
