app_devise:
    resource: "@AppBundle/Resources/config/routing/devise.yml"
    prefix:   /devise

app_fournisseurs:
    resource: "@AppBundle/Resources/config/routing/fournisseurs.yml"
    prefix:   /fournisseurs

app_produits:
    resource: "@AppBundle/Resources/config/routing/produits.yml"
    prefix:   /produits

app_proposition_fournisseurs:
    resource: "@AppBundle/Resources/config/routing/proposition_fournisseurs.yml"
    prefix:   /proposition_fournisseurs

app_type_produit:
    resource: "@AppBundle/Resources/config/routing/type_produit.yml"
    prefix:   /type_produit

app_vende:
    resource: "@AppBundle/Resources/config/routing/vende.yml"
    prefix:   /vende

app_user:
    resource: "@AppBundle/Resources/config/routing/user.yml"
    prefix:   /user

admin_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }
app_statfour:
        resource: "@AppBundle/Resources/config/routing/statfour.yml"
        prefix:   /statfour

app_client:
        resource: "@AppBundle/Resources/config/routing/client.yml"
        prefix:   /client

app_appareil:
        resource: "@AppBundle/Resources/config/routing/appareil.yml"
        prefix:   /appareil