AppBundle\Entity\type_produit:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\type_produitRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        type:
            type: string
            length: '50'
    oneToMany:
        produits:
            targetEntity: produits
            mappedBy: type_produit
    lifecycleCallbacks: {  }
